# Generated by Django 4.0.2 on 2022-02-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(db_column='identity_number', max_length=100)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('country', models.CharField(db_column='country', max_length=100)),
                ('province', models.CharField(db_column='province', max_length=100)),
                ('municipality', models.CharField(db_column='municipality', max_length=100)),
                ('situation', models.CharField(db_column='situation', max_length=100)),
                ('state', models.CharField(db_column='state', max_length=100)),
                ('address', models.CharField(db_column='address', max_length=100)),
                ('birth_date', models.DateField(db_column='birth_date', max_length=100)),
                ('group', models.CharField(db_column='group', max_length=100)),
                ('career', models.CharField(db_column='career', max_length=100)),
                ('faculty', models.CharField(db_column='faculty', max_length=100)),
                ('course_type', models.CharField(db_column='course_type', max_length=100)),
                ('mail', models.EmailField(db_column='mail', max_length=100)),
                ('source_of_income', models.CharField(db_column='source_of_income', max_length=100)),
                ('academic_origin', models.CharField(db_column='academic_origin', max_length=100)),
                ('study_regimen', models.CharField(db_column='study_regimen', max_length=100)),
                ('natural_from', models.CharField(db_column='natural_from', max_length=100)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=100)),
                ('es_income_date', models.DateField(db_column='es_income_date', max_length=100)),
                ('civil_state', models.CharField(db_column='civil_state', max_length=100)),
                ('political_organization', models.CharField(db_column='political_organization', max_length=100)),
                ('ces_income_date', models.DateField(db_column='ces_income_date', max_length=100)),
                ('enrollment_date', models.DateField(db_column='enrollment_date', max_length=100)),
                ('sex', models.CharField(db_column='sex', max_length=100)),
                ('skin_color', models.CharField(db_column='skin_color', max_length=100)),
                ('student_type', models.CharField(db_column='student_type', max_length=100)),
                ('study_year', models.CharField(db_column='study_year', max_length=100)),
                ('work_center', models.CharField(db_column='work_center', max_length=100)),
                ('fathers_name', models.CharField(db_column='fathers_name', max_length=100)),
                ('fathers_academic_level', models.CharField(db_column='fathers_academic_level', max_length=100)),
                ('mothers_name', models.CharField(db_column='mothers_name', max_length=100)),
                ('mothers_academic_level', models.CharField(db_column='mothers_academic_level', max_length=100)),
                ('military_service_type', models.CharField(db_column='military_service_type', max_length=100)),
                ('age', models.PositiveIntegerField(db_column='age')),
            ],
        ),
    ]
