# Generated by Django 4.0.2 on 2022-02-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identity_number',
            field=models.CharField(db_column='CI', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_column='Nombre', max_length=100),
        ),
    ]
