# Generated by Django 4.0.2 on 2022-02-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_rename_last_name_student_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CI',
            field=models.CharField(db_column='CI', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='apellidos',
            field=models.CharField(db_column='apellidos', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='año_de_Estudio',
            field=models.CharField(db_column='año_de_Estudio', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='carrera',
            field=models.CharField(db_column='carrera', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='centro_de_Trabajo',
            field=models.CharField(db_column='centro_de_Trabajo', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='color_de_Piel',
            field=models.CharField(db_column='color_de_Piel', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='correo_Electronico',
            field=models.EmailField(db_column='correo_Electronico', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='direccion',
            field=models.CharField(db_column='direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='edad',
            field=models.PositiveIntegerField(db_column='edad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='estado',
            field=models.CharField(db_column='estado', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='estado_Civil',
            field=models.CharField(db_column='estado_Civil', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='facultad',
            field=models.CharField(db_column='facultad', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_de_Ingreso_a_la_CES',
            field=models.DateField(db_column='fecha_de_Ingreso_a_la_CES', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_de_Ingreso_a_la_ES',
            field=models.DateField(db_column='fecha_de_Ingreso_a_la_ES', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_de_Matricula',
            field=models.DateField(db_column='fecha_de_Matricula', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_de_Nacimiento',
            field=models.DateField(db_column='fecha_de_Nacimiento', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fuente_de_Ingreso',
            field=models.CharField(db_column='fuente_de_Ingreso', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='grupo',
            field=models.CharField(db_column='grupo', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipio',
            field=models.CharField(db_column='municipio', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='natural_de',
            field=models.CharField(db_column='natural_de', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nivel_Academico_de_la_Madre',
            field=models.CharField(db_column='nivel_Academico_de_la_Madre', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nivel_Academico_del_Padre',
            field=models.CharField(db_column='nivel_Academico_del_Padre', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre_de_la_madre',
            field=models.CharField(db_column='nombre_de_la_madre', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre_del_Padre',
            field=models.CharField(db_column='nombre_del_Padre', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='numero_Telefonico',
            field=models.CharField(db_column='numero_Telefonico', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='organizacion_Politica',
            field=models.CharField(db_column='organizacion_Politica', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='origen_Academico',
            field=models.CharField(db_column='origen_Academico', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='pais',
            field=models.CharField(db_column='pais', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='provincia',
            field=models.CharField(db_column='provincia', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='regimen_de_Estudio',
            field=models.CharField(db_column='regimen_de_Estudio', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexo',
            field=models.CharField(db_column='sexo', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='situacion',
            field=models.CharField(db_column='situacion', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='tipo_de_Curso',
            field=models.CharField(db_column='tipo_de_Curso', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='tipo_de_Estudiante',
            field=models.CharField(db_column='tipo_de_Estudiante', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='tipo_de_Servicio_Militar',
            field=models.CharField(db_column='tipo_de_Servicio_Militar', max_length=100),
        ),
    ]
