# Generated by Django 4.0.2 on 2022-02-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_student_ci_alter_student_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='CI',
        ),
        migrations.RemoveField(
            model_name='student',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='student',
            name='año_de_Estudio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='student',
            name='centro_de_Trabajo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='color_de_Piel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='correo_Electronico',
        ),
        migrations.RemoveField(
            model_name='student',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='student',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='student',
            name='estado_Civil',
        ),
        migrations.RemoveField(
            model_name='student',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fecha_de_Ingreso_a_la_CES',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fecha_de_Ingreso_a_la_ES',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fecha_de_Matricula',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fecha_de_Nacimiento',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fuente_de_Ingreso',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='natural_de',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nivel_Academico_de_la_Madre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nivel_Academico_del_Padre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nombre_de_la_madre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nombre_del_Padre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='numero_Telefonico',
        ),
        migrations.RemoveField(
            model_name='student',
            name='organizacion_Politica',
        ),
        migrations.RemoveField(
            model_name='student',
            name='origen_Academico',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='student',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='student',
            name='regimen_de_Estudio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='situacion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tipo_de_Curso',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tipo_de_Estudiante',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tipo_de_Servicio_Militar',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_Origin',
            field=models.CharField(db_column='academic_origin', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(db_column='address', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(db_column='age', default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='birth_Date',
            field=models.DateField(db_column='birth_date', default='2000-1-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='career',
            field=models.CharField(db_column='career', default='Matematica', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ces_Income_Date',
            field=models.DateField(db_column='ces_income_date', default='2000-1-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='civil_State',
            field=models.CharField(db_column='civil_state', default='Single', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(db_column='country', default='Cuba', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course_Type',
            field=models.CharField(db_column='course_type', default='Daily', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_Date',
            field=models.DateField(db_column='enrollment_date', default='2000-1-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='es_Income_Date',
            field=models.DateField(db_column='es_income_date', default='2000-1-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(db_column='faculty', default='Matcom', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_Academic_Level',
            field=models.CharField(db_column='fathers_academic_level', default='Superior', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_Name',
            field=models.CharField(db_column='fathers_name', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(db_column='group', default='C111', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='identity_Number',
            field=models.CharField(db_column='identity_number', default='01010101011', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_Name',
            field=models.CharField(db_column='last_name', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.EmailField(db_column='mail', default='student@matcom.uh.cu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='military_Service_Type',
            field=models.CharField(db_column='military_service_type', default='Diferred', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_Academic_Level',
            field=models.CharField(db_column='mothers_academic_level', default='Superior', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_Name',
            field=models.CharField(db_column='mothers_name', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='municipality',
            field=models.CharField(db_column='municipality', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='natural_From',
            field=models.CharField(db_column='natural_from', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_Number',
            field=models.CharField(db_column='phone_number', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='political_Organization',
            field=models.CharField(db_column='political_organization', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(db_column='province', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(db_column='sex', default='Female', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='situation',
            field=models.CharField(db_column='situation', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='skin_Color',
            field=models.CharField(db_column='skin_color', default='White', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='source_of_Income',
            field=models.CharField(db_column='source_of_income', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(db_column='state', default='Single', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_Type',
            field=models.CharField(db_column='student_type', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='study_Regimen',
            field=models.CharField(db_column='study_regimen', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='study_Year',
            field=models.CharField(db_column='study_year', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='work_Center',
            field=models.CharField(db_column='work_center', default='', max_length=100),
            preserve_default=False,
        ),
    ]
