# Generated by Django 4.0.2 on 2022-02-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_remove_student_ci_remove_student_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_Origin',
            field=models.CharField(choices=[('Pre-universitary', 'Preuniversitary'), ('Foreign', 'Foreign'), ('Technical and Professional Learning', 'Technical And Professional Learning'), ('Order 18', 'Order 18')], default='Pre-universitary', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='career',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Math', 'Math')], default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='civil_State',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widower', 'Widower')], default='Single', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('Cuba', 'Cuba'), ('USA', 'Usa')], default='Cuba', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_Type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Nightly', 'Nightly')], default='Daily', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Matcom', 'Matcom')], default='Matcom', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathers_Academic_Level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Medium Superior', 'Medium Superior'), ('Superior', 'Superior')], default='Superior', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_Academic_Level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Medium Superior', 'Medium Superior'), ('Superior', 'Superior')], default='Superior', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipality',
            field=models.CharField(choices=[('Plaza de la revolucion', 'Plaza De La Revolucion'), ('Playa', 'Playa')], default='Playa', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(choices=[('La Habana', 'Habana'), ('Artemisa', 'Artemisa')], default='La Habana', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='situation',
            field=models.CharField(choices=[('New income', 'New Income'), ('Continuing', 'Continuing'), ('Repeating', 'Repeating'), ('Transfer', 'Transfer'), ('Re-entry', 'Reentry')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='skin_Color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Brown', 'Brown')], default='White', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='source_of_Income',
            field=models.CharField(choices=[('Pre-universitary', 'Preuniversitary'), ('Enabled Medium Superior', 'Enabled Medium Superior'), ('Decree 91', 'Decree 91'), ('Order 18', 'Order 18'), ('National Contests', 'National Contests'), ('MININT', 'Minint'), ('High Performance Athletes', 'High Performance Athletes'), ('Leveling Courses', 'Leveling Courses'), ('Foreign', 'Foreign')], default='Pre-universitary', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='New income', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Type',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Extern', 'Extern'), ('Half-Intern', 'Half Intern'), ('National Scolarship', 'National Scolarship'), ('International Scolarship', 'International Scolarship')], default='Extern', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_Regimen',
            field=models.CharField(choices=[('Only Study', 'Only Study'), ('Study and Work', 'Study And Work')], default='Only Study', max_length=100),
        ),
    ]
