from django.db import models

# Create your models here.
class Student(models.Model):
    identity_number = models.CharField(db_column='identity_number', max_length=100, blank=False)
    name = models.CharField(db_column='name', max_length=100, blank=False)
    last_name = models.CharField(db_column='last_name', max_length=100, blank=False)
    country = models.CharField(db_column='country', max_length=100, blank=False)
    province = models.CharField(db_column='province', max_length=100, blank=False)
    municipality = models.CharField(db_column='municipality', max_length=100, blank=False)
    situation = models.CharField(db_column='situation', max_length=100, blank=False)
    state = models.CharField(db_column='state', max_length=100, blank=False)
    address = models.CharField(db_column='address', max_length=100, blank=False)
    birth_date = models.DateField(db_column='birth_date', max_length=100, blank=False)
    group = models.CharField(db_column='group', max_length=100, blank=False)
    career = models.CharField(db_column='career', max_length=100, blank=False)
    faculty = models.CharField(db_column='faculty', max_length=100, blank=False)
    course_type = models.CharField(db_column='course_type', max_length=100, blank=False)
    mail = models.EmailField(db_column='mail', max_length=100, blank=False)
    source_of_income = models.CharField(db_column='source_of_income', max_length=100, blank=False)
    academic_origin = models.CharField(db_column='academic_origin', max_length=100, blank=False)
    study_regimen = models.CharField(db_column='study_regimen', max_length=100, blank=False)
    natural_from = models.CharField(db_column='natural_from', max_length=100, blank=False)
    phone_number = models.CharField(db_column='phone_number', max_length=100, blank=False)
    es_income_date = models.DateField(db_column='es_income_date', max_length=100, blank=False)
    civil_state = models.CharField(db_column='civil_state', max_length=100, blank=False)
    political_organization = models.CharField(db_column='political_organization', max_length=100, blank=False)
    ces_income_date = models.DateField(db_column='ces_income_date', max_length=100, blank=False)
    enrollment_date = models.DateField(db_column='enrollment_date', max_length=100, blank=False)
    sex = models.CharField(db_column='sex', max_length=100, blank=False)
    skin_color = models.CharField(db_column='skin_color', max_length=100, blank=False)
    student_type = models.CharField(db_column='student_type', max_length=100, blank=False)
    study_year = models.CharField(db_column='study_year', max_length=100, blank=False)
    work_center = models.CharField(db_column='work_center', max_length=100, blank=False)
    fathers_name = models.CharField(db_column='fathers_name', max_length=100, blank=False)
    fathers_academic_level = models.CharField(db_column='fathers_academic_level', max_length=100, blank=False)
    mothers_name = models.CharField(db_column='mothers_name', max_length=100, blank=False)
    mothers_academic_level = models.CharField(db_column='mothers_academic_level', max_length=100, blank=False)
    military_service_type = models.CharField(db_column='military_service_type', max_length=100, blank=False)
    age = models.PositiveIntegerField(db_column='age', blank=False)